# tasks/install_dependencies.yml
- name: Ensure Git is installed
  ansible.builtin.yum:
    name: git
    state: present

- name: Ensure Python3 is installed
  ansible.builtin.yum:
    name: python3
    state: present

- name: Ensure pip is installed
  ansible.builtin.yum:
    name: python3-pip
    state: present

- name: Ensure virtualenv is installed
  ansible.builtin.pip:
    name: virtualenv
    state: present
